"use client";

import { useEffect, useRef, useState } from "react";

// The wasm-bindgen module generated by `pnpm wasm:build` into public/renderer. It is loaded at
// runtime from /renderer, not bundled, so its type is declared here by hand.
interface WebViewer {
  frame(dt: number): void;
  take_requests(): Uint32Array;
  deliver(
    z: number,
    x: number,
    y: number,
    vertices: Uint8Array,
    features: Uint8Array,
    roofs: Uint8Array,
  ): void;
  fail(z: number, x: number, y: number): void;
  take_text_requests(): Float64Array;
  deliver_text(
    fileId: number,
    instances: Uint8Array,
    glyphCount: number,
    stripCount: number,
    firstLine: number,
    lineWorld: number,
  ): void;
  fail_text(fileId: number): void;
  text_stats(): Float64Array;
  resize(width: number, height: number): void;
  pointer_down(x: number, y: number): void;
  pointer_up(): void;
  pointer_move(x: number, y: number): void;
  wheel(notches: number): void;
  key(code: string, down: boolean): boolean;
  mode(): string;
  pick(x: number, y: number): Promise<number>;
  describe(id: number): string | undefined;
  worker_config(): string;
  drawn_tiles(): number;
  resident_tiles(): number;
  free(): void;
}

interface RendererModule {
  default: () => Promise<unknown>;
  WebViewer: {
    create(
      canvas: HTMLCanvasElement,
      manifestJson: string,
      paths: Uint8Array,
      tiles: Uint8Array,
    ): Promise<WebViewer>;
  };
}

type Status =
  | { kind: "loading" }
  | { kind: "ready" }
  | { kind: "unsupported" }
  | { kind: "error"; message: string };

// Physical-key codes the viewer understands. Some input sources (virtual keyboards, remote
// desktops, automation) send an empty KeyboardEvent.code, so fall back to the key value.
const KEY_TO_CODE: Record<string, string> = {
  w: "KeyW",
  a: "KeyA",
  s: "KeyS",
  d: "KeyD",
  q: "KeyQ",
  e: "KeyE",
};
function codeOf(e: KeyboardEvent): string {
  if (e.code) return e.code;
  return e.key.length === 1 ? (KEY_TO_CODE[e.key.toLowerCase()] ?? "") : e.key;
}

async function fetchBytes(url: string): Promise<Uint8Array> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} fetching ${url}`);
  return new Uint8Array(await res.arrayBuffer());
}

export function Viewer({ tileSetId, apiBase }: { tileSetId: string; apiBase: string }) {
  const mountRef = useRef<HTMLDivElement>(null);
  const [status, setStatus] = useState<Status>({ kind: "loading" });
  const [hover, setHover] = useState<string | null>(null);
  const [mode, setMode] = useState("map");
  const [stats, setStats] = useState({ drawn: 0, resident: 0, reading: 0 });

  useEffect(() => {
    const mount = mountRef.current;
    if (!mount) return;
    let disposed = false;
    let raf = 0;
    let viewer: WebViewer | null = null;
    const workers: Worker[] = [];
    const undo: Array<() => void> = [];

    (async () => {
      if (!("gpu" in navigator)) {
        setStatus({ kind: "unsupported" });
        return;
      }
      let mod: RendererModule;
      try {
        mod = (await import(
          /* webpackIgnore: true */ "/renderer/flyover_web.js" as string
        )) as RendererModule;
        await mod.default();
      } catch {
        setStatus({
          kind: "error",
          message: "The browser renderer isn't built yet. Run `pnpm wasm:build` and reload.",
        });
        return;
      }

      const base = `${apiBase}/tilesets/${encodeURIComponent(tileSetId)}/files`;
      const [manifest, paths, tiles] = await Promise.all([
        fetch(`${base}/manifest.json`).then((r) => {
          if (!r.ok) throw new Error(`${r.status} fetching the manifest`);
          return r.text();
        }),
        fetchBytes(`${base}/index/paths.bin`),
        fetchBytes(`${base}/index/tiles.bin`),
      ]);
      if (disposed) return;

      const canvas = document.createElement("canvas");
      canvas.tabIndex = 0;
      canvas.setAttribute("aria-label", "3D map of the repository");
      mount.appendChild(canvas);
      undo.push(() => canvas.remove());
      const measure = () => {
        const dpr = Math.min(window.devicePixelRatio || 1, 2);
        const r = mount.getBoundingClientRect();
        return {
          w: Math.max(1, Math.floor(r.width * dpr)),
          h: Math.max(1, Math.floor(r.height * dpr)),
          dpr,
        };
      };
      let { w, h, dpr } = measure();
      canvas.width = w;
      canvas.height = h;

      const v = await mod.WebViewer.create(canvas, manifest, paths, tiles);
      if (disposed) {
        v.free();
        return;
      }
      viewer = v;

      // Worker pool: fetch + decode + mesh off the main thread.
      const config = JSON.parse(v.worker_config());
      const poolSize = Math.max(2, Math.min(4, (navigator.hardwareConcurrency || 4) - 1));
      const queue: Array<[number, number, number]> = [];
      // Text is queued behind geometry: a roof with no building under it is nothing to read.
      const textQueue: Array<{ id: number; rect: number[]; z: number; firstLine: number }> = [];
      let inflight = 0;
      let turn = 0;
      const pump = () => {
        while (inflight < poolSize * 4 && queue.length > 0) {
          const [z, x, y] = queue.shift()!;
          workers[turn++ % poolSize]!.postMessage({ type: "tile", z, x, y, base });
          inflight++;
        }
        while (inflight < poolSize * 4 && textQueue.length > 0) {
          const job = textQueue.shift()!;
          workers[turn++ % poolSize]!.postMessage({ type: "text", ...job, base });
          inflight++;
        }
      };
      for (let i = 0; i < poolSize; i++) {
        const worker = new Worker("/flyover-worker.js", { type: "module" });
        worker.postMessage({ type: "config", config });
        worker.onmessage = (event: MessageEvent) => {
          inflight--;
          const m = event.data;
          if (m.type === "tile") v.deliver(m.z, m.x, m.y, m.vertices, m.features, m.roofs);
          else if (m.type === "text")
            v.deliver_text(m.id, m.instances, m.meta[0], m.meta[1], m.meta[2], m.meta[3]);
          else if (m.type === "textError") v.fail_text(m.id);
          else v.fail(m.z, m.x, m.y);
          pump();
        };
        workers.push(worker);
      }

      // Input. Canvas pixels are CSS pixels times the device pixel ratio.
      const at = (e: PointerEvent | WheelEvent) => {
        const r = canvas.getBoundingClientRect();
        return [(e.clientX - r.left) * dpr, (e.clientY - r.top) * dpr] as const;
      };
      let dragging = false;
      let pickPending = false;
      const listen = <K extends keyof HTMLElementEventMap>(
        target: HTMLElement | Window,
        type: K,
        fn: (e: HTMLElementEventMap[K]) => void,
        opts?: AddEventListenerOptions,
      ) => {
        target.addEventListener(type, fn as EventListener, opts);
        undo.push(() => target.removeEventListener(type, fn as EventListener, opts));
      };
      listen(canvas, "pointerdown", (e) => {
        canvas.focus();
        canvas.setPointerCapture(e.pointerId);
        dragging = true;
        v.pointer_down(...at(e));
      });
      listen(canvas, "pointerup", (e) => {
        canvas.releasePointerCapture(e.pointerId);
        dragging = false;
        v.pointer_up();
      });
      listen(canvas, "pointermove", (e) => {
        const [x, y] = at(e);
        if (dragging) {
          v.pointer_move(x, y);
          return;
        }
        if (pickPending) return;
        pickPending = true;
        v.pick(Math.floor(x), Math.floor(y))
          .then((id) => setHover(id ? (v.describe(id) ?? null) : null))
          .catch(() => setHover(null))
          .finally(() => (pickPending = false));
      });
      listen(canvas, "pointerleave", () => setHover(null));
      listen(
        canvas,
        "wheel",
        (e) => {
          e.preventDefault();
          const notches = e.deltaMode === 1 ? -e.deltaY : -e.deltaY / 100;
          v.wheel(notches);
        },
        { passive: false },
      );
      listen(canvas, "keydown", (e) => {
        if (v.key(codeOf(e), true)) {
          e.preventDefault();
          setMode(v.mode());
        }
      });
      listen(canvas, "keyup", (e) => {
        if (v.key(codeOf(e), false)) e.preventDefault();
      });
      listen(window, "blur", () => {
        for (const code of ["KeyW", "KeyA", "KeyS", "KeyD", "KeyQ", "KeyE"]) v.key(code, false);
      });

      const resizer = new ResizeObserver(() => {
        ({ w, h, dpr } = measure());
        if (w !== canvas.width || h !== canvas.height) {
          canvas.width = w;
          canvas.height = h;
          v.resize(w, h);
        }
      });
      resizer.observe(mount);
      undo.push(() => resizer.disconnect());

      const statTimer = window.setInterval(
        () =>
          setStats({
            drawn: v.drawn_tiles(),
            resident: v.resident_tiles(),
            reading: v.text_stats()[1] ?? 0,
          }),
        500,
      );
      undo.push(() => window.clearInterval(statTimer));

      let last = performance.now();
      const loop = (now: number) => {
        if (disposed) return;
        v.frame((now - last) / 1000);
        last = now;
        const req = v.take_requests();
        for (let i = 0; i + 2 < req.length; i += 3) queue.push([req[i]!, req[i + 1]!, req[i + 2]!]);
        const text = v.take_text_requests();
        for (let i = 0; i + 6 < text.length; i += 7) {
          textQueue.push({
            id: text[i]!,
            rect: [text[i + 1]!, text[i + 2]!, text[i + 3]!, text[i + 4]!],
            z: text[i + 5]!,
            firstLine: text[i + 6]!,
          });
        }
        pump();
        raf = requestAnimationFrame(loop);
      };
      raf = requestAnimationFrame(loop);
      setStatus({ kind: "ready" });
      canvas.focus();
    })().catch((err: unknown) => {
      if (!disposed) setStatus({ kind: "error", message: String(err) });
    });

    return () => {
      disposed = true;
      cancelAnimationFrame(raf);
      for (const worker of workers) worker.terminate();
      for (const fn of undo.reverse()) fn();
      viewer?.free();
    };
  }, [tileSetId, apiBase]);

  return (
    <div className="viewer-stage" ref={mountRef}>
      {status.kind === "ready" ? (
        <>
          <div className="hud hud-top">
            <span className="hud-chip">{mode === "fly" ? "Fly mode" : "Map mode"}</span>
            <span className="hud-chip muted">
              {stats.drawn} tiles drawn · {stats.resident} cached
              {stats.reading > 0 ? ` · ${stats.reading} readable` : ""}
            </span>
            {hover ? <span className="hud-chip strong">{hover}</span> : null}
          </div>
          <div className="hud hud-bottom">
            <span className="hud-help">
              {mode === "fly"
                ? "WASD move · Q/E down/up · drag to look · scroll for speed · Tab for map"
                : "Drag to orbit · scroll to zoom · WASD to pan · Tab to fly"}
            </span>
          </div>
        </>
      ) : (
        <div className="state">
          {status.kind === "loading" ? (
            <>
              <h3>Loading the map…</h3>
              <p>Starting WebGPU and fetching the tile index.</p>
            </>
          ) : status.kind === "unsupported" ? (
            <>
              <h3>This browser doesn’t support WebGPU</h3>
              <p>Use a recent Chrome, Edge, or Safari, or fly it natively with `flyover view`.</p>
            </>
          ) : (
            <>
              <h3>The viewer couldn’t start</h3>
              <p>{status.kind === "error" ? status.message : ""}</p>
            </>
          )}
        </div>
      )}
    </div>
  );
}
