//! The built-in exclusion list for vendored and generated code, applied on top of
//! .gitignore. Exclusions are recorded in the `excluded` table, never silently dropped.
//! `--include-vendored` turns every rule in here off.
//!
//! Directory rules prune the walk (so Chromium's `third_party` is never descended) and
//! record one row for the directory. File rules record one row per file.

/// Directory names that are pruned and recorded, matched on any path component.
pub const EXCLUDED_DIRS: &[&str] = &["node_modules", "third_party", "vendor", "dist"];

/// Dependency lockfiles: machine-written, huge, and not source.
const LOCKFILES: &[&str] = &[
    "Cargo.lock",
    "Gemfile.lock",
    "Pipfile.lock",
    "composer.lock",
    "go.sum",
    "npm-shrinkwrap.json",
    "package-lock.json",
    "pnpm-lock.yaml",
    "poetry.lock",
    "yarn.lock",
];

/// Markers a generator writes near the top of a file. Matched in the first sniff window.
const GENERATED_MARKERS: &[&[u8]] = &[
    b"@generated",
    b"@auto-generated",
    b"DO NOT EDIT",
    b"Code generated by",
    b"Generated by the protocol buffer compiler",
];

/// Why a path was excluded. The string form is stored in `excluded.reason`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reason {
    /// A pruned directory; the reason string is the directory name.
    Directory(&'static str),
    Lockfile,
    Minified,
    Generated,
}

impl Reason {
    pub fn as_str(self) -> &'static str {
        match self {
            Reason::Directory(name) => name,
            Reason::Lockfile => "lockfile",
            Reason::Minified => "minified",
            Reason::Generated => "generated",
        }
    }
}

/// A directory that should be pruned from the walk and recorded once.
pub fn excluded_dir(name: &str) -> Option<Reason> {
    EXCLUDED_DIRS
        .iter()
        .find(|d| **d == name)
        .map(|d| Reason::Directory(d))
}

/// A file excluded by name or suffix, decided before reading the file.
pub fn excluded_by_name(file_name: &str) -> Option<Reason> {
    if LOCKFILES.contains(&file_name) {
        return Some(Reason::Lockfile);
    }
    if file_name.ends_with(".min.js") || file_name.ends_with(".min.css") {
        return Some(Reason::Minified);
    }
    None
}

/// A file excluded because its header carries a generated-code marker. Only the first few lines
/// are scanned: a real generator writes its marker at the top, so a file that merely mentions
/// "@generated" or "DO NOT EDIT" further down (like this module) is not misclassified.
pub fn excluded_by_header(sniff: &[u8]) -> Option<Reason> {
    let header = header_window(sniff);
    if GENERATED_MARKERS.iter().any(|m| contains(header, m)) {
        Some(Reason::Generated)
    } else {
        None
    }
}

/// The header region: the first few lines, capped in bytes.
fn header_window(sniff: &[u8]) -> &[u8] {
    const MAX_LINES: usize = 5;
    const MAX_BYTES: usize = 2048;
    let cap = sniff.len().min(MAX_BYTES);
    let mut lines = 0;
    for (i, &b) in sniff[..cap].iter().enumerate() {
        if b == b'\n' {
            lines += 1;
            if lines == MAX_LINES {
                return &sniff[..=i];
            }
        }
    }
    &sniff[..cap]
}

/// Naive substring search over the sniff window (a few KB at most).
fn contains(haystack: &[u8], needle: &[u8]) -> bool {
    if needle.is_empty() || needle.len() > haystack.len() {
        return false;
    }
    haystack.windows(needle.len()).any(|w| w == needle)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dirs_match_by_name_only() {
        assert_eq!(
            excluded_dir("node_modules"),
            Some(Reason::Directory("node_modules"))
        );
        assert_eq!(
            excluded_dir("third_party"),
            Some(Reason::Directory("third_party"))
        );
        assert_eq!(excluded_dir("src"), None);
    }

    #[test]
    fn names_catch_lockfiles_and_minified() {
        assert_eq!(excluded_by_name("pnpm-lock.yaml"), Some(Reason::Lockfile));
        assert_eq!(excluded_by_name("Cargo.lock"), Some(Reason::Lockfile));
        assert_eq!(excluded_by_name("app.min.js"), Some(Reason::Minified));
        assert_eq!(excluded_by_name("styles.min.css"), Some(Reason::Minified));
        assert_eq!(excluded_by_name("main.rs"), None);
    }

    #[test]
    fn header_catches_generated_markers() {
        assert_eq!(
            excluded_by_header(b"// @generated by tool\ncode"),
            Some(Reason::Generated)
        );
        assert_eq!(
            excluded_by_header(b"/* DO NOT EDIT */\n"),
            Some(Reason::Generated)
        );
        assert_eq!(excluded_by_header(b"fn main() {}\n"), None);
    }

    #[test]
    fn marker_below_the_header_is_not_a_match() {
        // A file that only mentions the marker deeper down is real source, not generated.
        let mut src = b"line1\nline2\nline3\nline4\nline5\nline6\n".to_vec();
        src.extend_from_slice(b"// @generated appears here but too late\n");
        assert_eq!(excluded_by_header(&src), None);
    }

    #[test]
    fn reason_strings_are_stable() {
        assert_eq!(Reason::Directory("node_modules").as_str(), "node_modules");
        assert_eq!(Reason::Lockfile.as_str(), "lockfile");
        assert_eq!(Reason::Minified.as_str(), "minified");
        assert_eq!(Reason::Generated.as_str(), "generated");
    }
}
